### PR TITLE
A robust general framework for I/O

### PR DESCRIPTION
**Pull request by ctrueden**
This branch introduces a framework for I/O, particularly random access I/O. Where data comes from is now fully extensible: create a new `Location` type—and optionally a corresponding `DataHandle` plugin that wraps it—to define new paradigms of data access and storage.

Main points of the design:
* All data is identified by `Location` objects of a particular type.
* The new `DataTypeService` is a `WrapperService` that matches up `Location` objects with `DataHandle` plugin wrappers that know how to provide random access into the location's bytes etc.
    * Initially, a `FileHandle` is provided for access to `FileLocation`s (which are in turn backed by `java.io.File`).
    * Adding the other `DataHandle` plugins later will be relatively straightforward, especially after porting over SCIFIO's `io.scif.io.StreamHandle` abstract class layer.
* For better type richness, all concrete `IOPlugin` implementations will operate on `Location` objects instead of `String`. This branch holds off on that change for the moment though, since it is a breaking API change.

Benefits for SCIFIO:
* SCIFIO `Format` plugins will be able to operate on `Location` objects instead of plain `String`s.
* For `Format` plugins that prefer to operate on the `DataHandle` level, they can ask the `DataHandleService` for a `DataHandle` corresponding to a particular `Location`, then inspect the data itself at various phases (any or all of `Checker`, `Parser`, `Reader` and `Writer`).
* Some `Format` plugins may opt to accept only a specific type of `Location`, ignoring the `DataHandle` API. For example, the `OMEROFormat` of [ImageJ-OMERO](https://github.com/imagej/imagej-omero) will accept only `OMEROLocation` objects, extracting the relevant information from the `OMEROLocation` (server name, user name, session ID, etc.) and using it to make the specified OMERO connection and extract the pixels and metadata that way.
* All of `io.scif.io` can likely be removed from the codebase, in favor of this framework. (And in general: eventually, all of `io.scif.common` should be migrated to SJC.)

See also these issues, some of which will be resolved by this work:
* scifio/scifio#75
* scifio/scifio#86
* scifio/scifio#146
* scifio/scifio#181
* scifio/scifio#235
* scifio/scifio#237
* scifio/scifio#251
* imagej/imagej#104
* knime-ip/knip-omero#2

### CODE REVIEW

**Comment by ctrueden** [comment]
@hinerm I would greatly appreciate your feedback. This work was the main blocker for merging the other `3.0.0` PRs, so if this looks good we can go ahead and finish up the SJC3 release very soon.

**Comment by ctrueden** [comment]
See also these issues, some of which will be resolved by this work:
* scifio/scifio#75
* scifio/scifio#86
* scifio/scifio#146
* scifio/scifio#181
* scifio/scifio#235
* scifio/scifio#237
* scifio/scifio#251
* imagej/imagej#104
* knime-ip/knip-omero#2

**Comment by hinerm** [comment]
Looks good to me. Such nice atomic changes!

**Comment by ctrueden** [comment]
I merged it, without the breaking `IOPlugin` API changes. I have started a separate PR for those: #167.

**Pull request merged**
