### PR TITLE
Locale fixes

### PR DESCRIPTION
**Pull request by hinerm**
Makes UnitUtils non-US-centric, and updates the corresponding unit test to pass in non-US locales.

### CODE REVIEW

**Comment by hinerm** [comment]
@gab1one Would you mind checking out this branch and building it on your machine? It changes the fix you submitted last week to not force US Locale, but instead format the test strings for the current locale.. just want to be sure the unit tests don't fail for you now. Thanks!

**Comment by gab1one** [comment]
Sadly that does not work at all (the local() method has no effect), I think we need to split the number from the unit or something.

**Comment by hinerm** [comment]
>I think we need to split the number from the unit or something.

@gab1one yep I agree. When the test strings contain the numeric value + label, they don't get numeric formatting.

Anyway I force pushed a new patch set that should format the test strings the same as UnitUtils. Can you test again?

Much thanks.

**Comment by gab1one** [comment]
It works now, thank you :+1:

**Pull request merged**
