### PR TITLE
Avoid displaying welcome message when running headless

### PR DESCRIPTION
**Pull request by imagejan**
As suggested by @ctrueden in [this discussion](http://forum.imagej.net/t/running-fiji-in-headless-mode-inside-docker-container/7626/3?u=imagejan) on the forum.

I didn't have a chance to test this headless yet, so please test before merging.

/cc @sebi06

### CODE REVIEW

**Comment by ctrueden** [comment]
@imagejan When you get a chance, could you please rebase this over the latest master and then force push? I'd like to see if it fixes the Travis build.

**Comment by imagejan** [comment]
@ctrueden wrote:
> When you get a chance, could you please rebase this over the latest master and then force push?

I did, but Travis still seems to have problems...

**Comment by ctrueden** [comment]
> Travis still seems to have problems...

As [mentioned in Gitter](https://gitter.im/scijava/scijava-common?at=59f79dbc614889d4751da487), but repeated here for the benefit of others: I pushed a commit to scijava-common which I hope finally fixes the issue: https://github.com/scijava/scijava-common/commit/a00f50de7e84b3d04b9529df839ac92043d2652c. More importantly, I pushed a fix to `travisify.sh` which will set up new projects correctly in the future: https://github.com/scijava/scijava-scripts/commit/56f0f6efd49e544bb50f489fe9e5963cb1865693. So hopefully another rebase against latest SJC master followed by force push of your PR will now, finally, have a successful Travis build. Thank you for bearing with me with this unrelated-but-important-to-address issue.

**Comment by ctrueden** [comment]
@imagejan It was a fluke. I told Travis to restart the build and it worked.

**Comment by ctrueden** [comment]
Thanks for fixing this!

**Pull request merged**
