### PR TITLE
Add array conversion classes

### PR DESCRIPTION
**Pull request by hinerm**
Adds converters for going between analogous primitive array (and list) types.

### CODE REVIEW

**Comment by hinerm** [comment]
Needs unit tests.

**Comment by hinerm** [comment]
@ctrueden @bnorthan - updated and working now, I hope.

**Comment by bnorthan** [comment]
@hinerm 

It is still not working in python, I think it because 'python lists' don't get converted to 'Dimensions'.  'Python lists' do get converted to 'java arrays', and java arrays get converted to 'Dimensions', but 'python lists' don't get converted to 'Dimensions'

``` python
# this one works...
phantom=ops.create().img(array([xSize, ySize], 'l'))

# so does this one...
phantom=ops.create().img(FinalDimensions([xSize,ySize]))

# this one does not....
phantom=ops.create().img([xSize, ySize])
```

**Comment by hinerm** [comment]
Yeah there were several fixes required at various layers.

>phantom=ops.create().img([xSize, ySize])

This is addressed https://github.com/imagej/imagej-ops/commit/becc4904fb639f6835a127a7d9e30112f1c593fb should fix

**Comment by hinerm** [comment]
>>'Python lists' do get converted to 'java arrays'

>This requires a separate converter, which is incoming! Then this will work:

I lied! I thought you were referring to failures when passing an array + another argument, e.g. a `Type`, which wasn't working. But actually this already works without the need for a custom converter, because of the `List > FinalDimensions` converter:

```
ops.create().img([xSize, ySize], LongType())
```

**Pull request merged**
