### PR TITLE
Revamp the LogService

### PR DESCRIPTION
**Pull request by ctrueden**
Continuation of #253 and #255.

### CODE REVIEW

**Comment by maarzt** [comment]
:heart:  You simplified a lot of stuff :+1:

The last four commits regarding RootLogger are a bit confusing.
You are right: DefaultLogger should be an AbstractLogger, because it's not
used as DefaultLogger but instead used as base class for inheritance.

**Comment by maarzt** [comment]
Hi @ctrueden, @fjug desperately wants this stuff for developing his Tr2dy plugin.
Do you think we can merge it until the Hackathon in Kontanz?

**Comment by maarzt** [comment]
Hi @ctrueden, @fjug desparetly wants this stuff to developing his Tr2dy plugin.
Do you think we can merge it before the Kontanz Hackathon?

**Comment by ctrueden** [comment]
> Do you think we can merge it until the Hackathon in Kontanz?

Well, the current state of the branch is a huge mess. It does not merge cleanly, and there are a bunch of WIPs. In short, the branch still needs a substantial amount of work before it can be merged, and I do not have time to work on it myself. If you guys want it merged before Konstanz, you'll have to present a clean, mergeable branch with good unit test coverage. If you are able to do that before Monday, September 11, I'll make time to review it then before the hackathon, with the goal if getting it merged to master that week. It would be ideal if you were available that week for at least one more iteration of review and discussion, since I expect we'll still have some kinks to iron out.

**Comment by maarzt** [comment]
I have an idea how to eliminate the strange `LogLevelStrategy` class.
I will finish implementing it this evening, so that the branch is ready to be reviewed tomorrow.

**Comment by maarzt** [comment]
Hi @ctrueden, the branch is ready to be reviewed. I rewrote the history to get rid of the WIP commits. Now it should be nice an clean. No changes in it that are later reverted and so one. And I god rid of the package-private `LogLevelStrategy` and `DefaultLogger` is really the default logger.

**Comment by maarzt** [comment]
I added many tests to ensure, that there are no API changes breaking client code. see https://github.com/scijava/scijava-common/pull/272/commits/93dffbdd164f06a39bd6636d66824ab605d0c6ed
This is actually the first commit of the branch. Github shows the commits strangle ordered. Probably because I used git rebase a lot.

I available the whole week for discussions, or if I should change something. @ctrueden hope you're not too busy and we can work on this, this week.

**Comment by ctrueden** [comment]
Thanks for your efforts, @maarzt! I am out sick today, but will try to follow up on this as soon as I feel better.

**Comment by ctrueden** [comment]
I started looking through the commits yesterday, and got about halfway through. Will continue today.

**Comment by maarzt** [comment]
Nice! Is there already something you which to discuss?

**Comment by ctrueden** [comment]
> Is there already something you which to discuss?

Not yet. I am looking at cherry-picking some of the standalone improvements you made onto master right away, to cut down on this monster. I rebased over latest master, will rebase again to fix very small issues (e.g. typos in commit messages), and force push that later today. For substantive changes etc., I have some commits I've done on top of the branch, which I will also push.

I think the sanest plan would be for you to look over my new commits between now and next Wednesday, and then we can merge it together on Wednesday at the hackathon.

I'll comment here again after I do the pushes.

**Comment by maarzt** [comment]
What's the current status, guess you got stuck somewhere?

Maybe I can help cutting the monster? Tell me which commits you consider as standalone changes. I can then put them to the beginning of this branch, to make them easier to be merged separately.

**Comment by ctrueden** [comment]
Sorry, I ran out of time. I will try to work on it again today, and/or on
my flight, but it might have to wait till Konstanz.

**Comment by ctrueden** [comment]
13 of the commits are now merged to master. But there are still 23 to go.

**Comment by ctrueden** [comment]
I am now done massaging the commits. I think it is looking pretty good. There are three commits I still want to discuss, which I moved to a separate branch `log-recorder`, on top of this one.

@maarzt Please take a look and let me know what you think. We can hash out remaining issues in person when you arrive at the hackathon.

**Comment by maarzt** [comment]
I did a force push because: There where some commits fixing other commits. I squashed them, so the dirty code never appears in the history.

I sorted the commits, by the changes made:
1. Make LogService Listenable
2. Add sub loggers
3. Add LogPreprocessor
4. Miscellaneous stuff

**Comment by ctrueden** [comment]
@maarzt Great. All the commits compile with passing tests. If you have no objections, I will merge now. We can discuss the `LogRecorder` next!

**Pull request merged**
