### PR TITLE
Fix array types with generics

### PR DESCRIPTION
**Pull request by NicoKiaru**
Adds a test that reproduces the issue https://github.com/scijava/scijava-common/issues/415

The test CommandArrayConverterTest#testArrayConvertFromStringCommandWildcardGenerics currently fails

### CODE REVIEW

**Comment by imagejan** [comment]
@hinerm if you find the time, may I ask you to have a look at this? See the linked issues for context.

**Comment by hinerm** [comment]
This was a delightfully effortless PR to review and merge. Thank you so much @imagejan, @NicoKiaru, @frauzufall!

**Comment by imagejan** [comment]
@hinerm thanks a lot!

Did you merge locally? I would have expected the merge of this PR make #417 obsolete, but now it's still open because the commit hashes of the PR branches (both #416 and #417) are different from the ones on `master` 😕 

Will close the other PR manually.

**Comment by NicoKiaru** [comment]
@hinerm do you know if this fix made its way in pom-scijava 30.0.0 ? Or is it planned for 30.0.1 ? Or is it unrelated ?

**Comment by imagejan** [comment]
@NicoKiaru if you click on the merge commit of this PR (https://github.com/scijava/scijava-common/commit/c7aa9f497534cb23765a8af80b4d4caa117d3a05), you'll see only `master` but no tags in the subtitle:

image

... meaning that this commit is not (yet) part of any *release* of `scijava-common`. We first need a release of this component, then a version bump in `pom-scijava`, then a release of a new `pom-scijava`. Until then, you'll have to pin to a SNAPSHOT release for development.

**Comment by NicoKiaru** [comment]
Thanks as always @imagejan !

**Pull request merged**
